# Generated by Django 4.1.5 on 2023-01-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='name',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
