# Generated by Django 4.1.5 on 2023-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_saleorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderline',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='unit_total',
            field=models.IntegerField(),
        ),
    ]
