# Generated by Django 4.1.5 on 2023-01-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='order_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_sale_order', to='forms.saleorder'),
        ),
    ]
