# Generated by Django 4.1.5 on 2023-01-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_tag_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='order_id',
        ),
        migrations.AddField(
            model_name='saleorderline',
            name='tags',
            field=models.ManyToManyField(related_name='tag_sale_order', to='forms.tag'),
        ),
    ]
